import { ContentItem } from './supabase';

// Demo data for testing without Supabase
export const MOCK_CONTENT: ContentItem[] = [
  {
    id: 'demo-1',
    platform: 'tiktok',
    external_id: '7331234567890123456',
    url: 'https://www.tiktok.com/@cutecats/video/7331234567890123456',
    embed_code: null,
    thumbnail_url: 'https://picsum.photos/seed/cat1/400/711',
    video_url: null,
    title: null,
    description: 'My cat trying to catch the laser pointer 😂 #cats #catsoftiktok #funny',
    creator_name: 'CuteCats',
    creator_url: 'https://www.tiktok.com/@cutecats',
    creator_avatar: 'https://picsum.photos/seed/avatar1/100/100',
    likes: 1250000,
    shares: 45000,
    comments: 23000,
    views: 8500000,
    scraped_at: new Date().toISOString(),
    is_active: true,
    trending_score: 9.8,
    raw_data: null,
  },
  {
    id: 'demo-2',
    platform: 'youtube',
    external_id: 'dQw4w9WgXcQ',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    embed_code: null,
    thumbnail_url: 'https://picsum.photos/seed/cat2/400/711',
    video_url: null,
    title: 'Fluffy Persian kitten compilation',
    description: 'Watch this adorable Persian kitten enjoy the sunshine ☀️ #cats #kitten',
    creator_name: 'PetLovers',
    creator_url: 'https://www.youtube.com/@PetLovers',
    creator_avatar: 'https://picsum.photos/seed/avatar2/100/100',
    likes: 89000,
    shares: 5000,
    comments: 1200,
    views: 2500000,
    scraped_at: new Date().toISOString(),
    is_active: true,
    trending_score: 8.5,
    raw_data: null,
  },
  {
    id: 'demo-3',
    platform: 'xiaohongshu',
    external_id: '6574839201234567',
    url: 'https://www.xiaohongshu.com/explore/6574839201234567',
    embed_code: null,
    thumbnail_url: 'https://picsum.photos/seed/cat3/400/711',
    video_url: null,
    title: '我家猫咪的日常',
    description: '记录我家小橘猫的日常生活，太可爱了！#猫咪 #萌宠 #橘猫',
    creator_name: '猫咪日记',
    creator_url: 'https://www.xiaohongshu.com/user/profile/123456',
    creator_avatar: 'https://picsum.photos/seed/avatar3/100/100',
    likes: 52000,
    shares: 3400,
    comments: 890,
    views: null,
    scraped_at: new Date().toISOString(),
    is_active: true,
    trending_score: 7.9,
    raw_data: null,
  },
  {
    id: 'demo-4',
    platform: 'youtube',
    external_id: 'abc123xyz',
    url: 'https://www.youtube.com/watch?v=abc123xyz',
    embed_code: null,
    thumbnail_url: 'https://picsum.photos/seed/cat4/400/711',
    video_url: null,
    title: 'Golden Retriever sees snow for the first time',
    description: 'Watch this adorable Golden Retriever experience snow! 😂 #dogs #goldenretriever',
    creator_name: 'DoggyWorld',
    creator_url: 'https://www.youtube.com/@DoggyWorld',
    creator_avatar: 'https://picsum.photos/seed/avatar4/100/100',
    likes: 2100000,
    shares: 89000,
    comments: 45000,
    views: 15000000,
    scraped_at: new Date().toISOString(),
    is_active: true,
    trending_score: 9.5,
    raw_data: null,
  },
  {
    id: 'demo-5',
    platform: 'tiktok',
    external_id: '7332345678901234567',
    url: 'https://www.tiktok.com/@puppylove/video/7332345678901234567',
    embed_code: null,
    thumbnail_url: 'https://picsum.photos/seed/dog1/400/711',
    video_url: null,
    title: null,
    description: 'Golden retriever puppy meets snow for the first time! ❄️🐕 #puppies #goldenretriever #cute',
    creator_name: 'PuppyLove',
    creator_url: 'https://www.tiktok.com/@puppylove',
    creator_avatar: 'https://picsum.photos/seed/avatar5/100/100',
    likes: 3400000,
    shares: 120000,
    comments: 67000,
    views: 22000000,
    scraped_at: new Date().toISOString(),
    is_active: true,
    trending_score: 9.9,
    raw_data: null,
  },
  {
    id: 'demo-6',
    platform: 'youtube',
    external_id: 'def456uvw',
    url: 'https://www.youtube.com/watch?v=def456uvw',
    embed_code: null,
    thumbnail_url: 'https://picsum.photos/seed/cat5/400/711',
    video_url: null,
    title: 'Cats being cats compilation',
    description: 'When your cat judges your life choices 😹 #cats #catmemes #funny',
    creator_name: 'FunnyCats',
    creator_url: 'https://www.youtube.com/@FunnyCats',
    creator_avatar: 'https://picsum.photos/seed/avatar6/100/100',
    likes: 156000,
    shares: 8000,
    comments: 4500,
    views: 3200000,
    scraped_at: new Date().toISOString(),
    is_active: true,
    trending_score: 8.8,
    raw_data: null,
  },
  {
    id: 'demo-7',
    platform: 'xiaohongshu',
    external_id: '6574839201234568',
    url: 'https://www.xiaohongshu.com/explore/6574839201234568',
    embed_code: null,
    thumbnail_url: 'https://picsum.photos/seed/cat6/400/711',
    video_url: null,
    title: '布偶猫的一天',
    description: '我家布偶真的太粘人了，走哪跟哪 💕 #布偶猫 #猫咪 #萌宠日常',
    creator_name: '布偶控',
    creator_url: 'https://www.xiaohongshu.com/user/profile/789012',
    creator_avatar: 'https://picsum.photos/seed/avatar7/100/100',
    likes: 78000,
    shares: 5600,
    comments: 2100,
    views: null,
    scraped_at: new Date().toISOString(),
    is_active: true,
    trending_score: 8.2,
    raw_data: null,
  },
  {
    id: 'demo-8',
    platform: 'youtube',
    external_id: 'ghi789rst',
    url: 'https://www.youtube.com/watch?v=ghi789rst',
    embed_code: null,
    thumbnail_url: 'https://picsum.photos/seed/dog2/400/711',
    video_url: null,
    title: 'Shiba Inu being dramatic',
    description: 'My Shiba Inu has the most expressive faces 😆 #shiba #dogs #funny',
    creator_name: 'ShibaLife',
    creator_url: 'https://www.youtube.com/@ShibaLife',
    creator_avatar: 'https://picsum.photos/seed/avatar8/100/100',
    likes: 890000,
    shares: 34000,
    comments: 12000,
    views: 5600000,
    scraped_at: new Date().toISOString(),
    is_active: true,
    trending_score: 9.1,
    raw_data: null,
  },
  {
    id: 'demo-9',
    platform: 'tiktok',
    external_id: '7333456789012345678',
    url: 'https://www.tiktok.com/@catlovers/video/7333456789012345678',
    embed_code: null,
    thumbnail_url: 'https://picsum.photos/seed/cat7/400/711',
    video_url: null,
    title: null,
    description: 'Cat vs cucumber - the eternal battle continues 🥒😺 #cats #funny #cucumber',
    creator_name: 'CatLoversClub',
    creator_url: 'https://www.tiktok.com/@catlovers',
    creator_avatar: 'https://picsum.photos/seed/avatar9/100/100',
    likes: 567000,
    shares: 23000,
    comments: 8900,
    views: 3200000,
    scraped_at: new Date().toISOString(),
    is_active: true,
    trending_score: 8.7,
    raw_data: null,
  },
  {
    id: 'demo-10',
    platform: 'youtube',
    external_id: 'jkl012mno',
    url: 'https://www.youtube.com/watch?v=jkl012mno',
    embed_code: null,
    thumbnail_url: 'https://picsum.photos/seed/dog3/400/711',
    video_url: null,
    title: 'Service dog in training',
    description: 'Service dog in training 🦮❤️ So proud of this good boy! #servicedog #dogs',
    creator_name: 'ServicePups',
    creator_url: 'https://www.youtube.com/@ServicePups',
    creator_avatar: 'https://picsum.photos/seed/avatar10/100/100',
    likes: 234000,
    shares: 15000,
    comments: 6700,
    views: 4100000,
    scraped_at: new Date().toISOString(),
    is_active: true,
    trending_score: 8.4,
    raw_data: null,
  },
  {
    id: 'demo-11',
    platform: 'xiaohongshu',
    external_id: '6574839201234569',
    url: 'https://www.xiaohongshu.com/explore/6574839201234569',
    embed_code: null,
    thumbnail_url: 'https://picsum.photos/seed/cat8/400/711',
    video_url: null,
    title: '英短蓝猫的傲娇时刻',
    description: '我家蓝猫真的太高冷了，叫它都不理 😂 #英短 #蓝猫 #猫咪',
    creator_name: '蓝猫之家',
    creator_url: 'https://www.xiaohongshu.com/user/profile/345678',
    creator_avatar: 'https://picsum.photos/seed/avatar11/100/100',
    likes: 45000,
    shares: 2800,
    comments: 980,
    views: null,
    scraped_at: new Date().toISOString(),
    is_active: true,
    trending_score: 7.6,
    raw_data: null,
  },
  {
    id: 'demo-12',
    platform: 'tiktok',
    external_id: '7334567890123456789',
    url: 'https://www.tiktok.com/@happyfamily/video/7334567890123456789',
    embed_code: null,
    thumbnail_url: 'https://picsum.photos/seed/cat9/400/711',
    video_url: null,
    title: null,
    description: 'Cat and baby best friends forever 🥰 #cats #baby #wholesome',
    creator_name: 'HappyFamily',
    creator_url: 'https://www.tiktok.com/@happyfamily',
    creator_avatar: 'https://picsum.photos/seed/avatar12/100/100',
    likes: 1560000,
    shares: 67000,
    comments: 28000,
    views: 9800000,
    scraped_at: new Date().toISOString(),
    is_active: true,
    trending_score: 9.3,
    raw_data: null,
  },
];

export function getMockContent(
  platform: string,
  sort: string,
  cursor: string | null,
  limit: number
): { items: ContentItem[]; nextCursor: string | null; hasMore: boolean } {
  let filtered = [...MOCK_CONTENT];

  // Filter by platform
  if (platform && platform !== 'all') {
    filtered = filtered.filter(item => item.platform === platform);
  }

  // Sort
  switch (sort) {
    case 'trending':
      filtered.sort((a, b) => b.trending_score - a.trending_score);
      break;
    case 'recent':
      filtered.sort((a, b) => new Date(b.scraped_at).getTime() - new Date(a.scraped_at).getTime());
      break;
    case 'likes':
      filtered.sort((a, b) => b.likes - a.likes);
      break;
  }

  // Cursor pagination
  let startIndex = 0;
  if (cursor) {
    const cursorIndex = filtered.findIndex(item => item.id === cursor);
    if (cursorIndex !== -1) {
      startIndex = cursorIndex + 1;
    }
  }

  const items = filtered.slice(startIndex, startIndex + limit);
  const hasMore = startIndex + limit < filtered.length;
  const nextCursor = hasMore ? items[items.length - 1]?.id || null : null;

  return { items, nextCursor, hasMore };
}
